name: Push Docker Images

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker tag Pipe Image 
      run: docker tag $(docker images api-server -q) azbuilder/terrakube-pipe:$VERSION
      
    - name: Docker tag Pipe Image latest
      run: docker tag $(docker images api-server -q) azbuilder/terrakube-pipe:latest
    
    - name: Docker Push Pipe 
      run: docker push azbuilder/terrakube-pipe:$VERSION
      
    - name: Docker Push Pipe latest
      run: docker push azbuilder/terrakube-pipe:latest
    